server:
  port: 8080 # 충돌 문제 시 수정
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 10 # 최대 커넥션 수
      minimum-idle: 5 # 최소 유휴 커넥션 수
  profiles:
    active: dev
  springdoc:
    swagger-ui:
      path: /swagger-ui.html

jpa:
  hibernate:
    ddl-auto: none
  show-sql: true # SQL 로그 출력
  properties:
    hibernate:
      format_sql: true # SQL 예쁘게 출력
  open-in-view: false # OSIV 비활성화 (API 서버라면 false 추천)

mybatis:
  type-handlers-package: com.team05.linkup.common.config.mybatis
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.team05.linkup.domain
  configuration:
    map-underscore-to-camel-case: true

